### ISSUE TITLE
Need testing sufficient at least for dependabot PRs

### ISSUE THREAD

**Issue by gwhitney** [numberscope/backscope#11]
This issue is a placeholder for the effort to get some modicum of testing in place. With even just a little basic automated unit and/or integration testing in place, maintainers could routinely merge the dependabot PRs with no further inspection.

**Comment by liam-mulhall** [comment]
Related to https://github.com/numberscope/backscope/issues/44.

**Comment by liammulh** [comment]
I'm not working on this right now. Unassigning myself.

**Comment by gwhitney** [comment]
I think this is covered by #84. Seems adequate for testing dependabot PRs, and should improve over time.
