### ISSUE TITLE
`flask test -v` should show diffs

### ISSUE THREAD

**Issue by gwhitney** [numberscope/backscope#116]
I am running into a test failure in the current state of #111. At the end of the failure report, it says

```
Diff is 6546 characters long. Set self.maxDiff to None to see it.
```

I re-ran with `flask test -v`. It seems to me that in verbose mode, it should always show the diffs.
I will work on a PR to that effect, in case @katestange @Vectornaut agree.
(In any case, a way to see the diffs would be handy in investigating what is going on in #111; so if this suggestion doesn't seem good, please recommend another convenient way to see the diffs.)

**Comment by katestange** [comment]
That seems to make sense to me.

**Comment by gwhitney** [comment]
OK, up to @Vectornaut whether to merge this first or #111 first, since he's the one that would be affected by it.
