### ISSUE TITLE
Establish protocol for installing and deploying backscope on the Numberscope server

### ISSUE THREAD

**Issue by gwhitney** [numberscope/backscope#15]
The README etc. now makes getting a local copy of the server running relatively clear and straightforward, but it seems at least at first glance that exactly what should be done for it to run and be publicly accessible on numberscope.colorado.edu is less clear, especially as relates to updating that server when new code is committed to the official backscope repository. The procedure for doing this should be codified, tested, and clearly documented.

**Comment by gwhitney** [comment]
Great, so the detailed docs are now in place. When someone has the opportunity to follow through them and actually get backscope running on the server, they should make any changes in the procedure to reflect what happened, as well as add the auxiliary files needed in the deployment as separate files in the repository (with placeholders for any secrets), and make another PR with those things. Then we can close this issue :)

**Comment by liam-mulhall** [comment]
Most (all?) of the info in this issue will be outdated when Jeff updates the server to a new version of Debian. Also, this isn't specific to backscope. Also, I'm making a project for this. Closing.
