### ISSUE TITLE
Backend is not using the database to cache sequence values

### ISSUE THREAD

**Issue by gwhitney** [numberscope/backscope#22]
Looking at the actual code, the backend is not using the database that is being set up for it to store the results of its queries to the OEIS files. Instead it is using a set of plain-text files in a temp directory. UNIX filesystems used in this way are not necessarily "atomic" so if there are two requests in succession for the same sequence, one might produce garbage. The sequence data should be stored/retrieved from the database; such operations are atomic.

**Comment by liam-mulhall** [comment]
Assuming the Postgres version on the server is greater than 9.2, we could store JSON in the database. Here are tutorials that might help:

* https://www.postgresqltutorial.com/postgresql-json/
* https://www.blendo.co/blog/storing-json-in-postgresql/

Here are the docs for the current version of Postgres:

* https://www.postgresql.org/docs/14/datatype-json.html

**Comment by gwhitney** [comment]
A solution to this should determine a response to #25 and implement that as well.

**Comment by gwhitney** [comment]
In particular, there is not yet any database design for storing sequence entries. The table "sequences" has just three columns: "id," "name," and "first_100_entries," which is obviously inadequate for storing actual OEIS sequence data. An appropriate database representation for sequences needs to be designed and implemented, one that can handle whatever we decide to do about offsets (see #25) and which can also store the name (as is clearly currently contemplated) and cross references (see #17), as well as facilitate the generation and storage of factorizations (see #12) and possibly discrete fourier transforms (see #18).

**Comment by gwhitney** [comment]
>we could store JSON in the database if we wanted to. 

If we decide to store sequences as JSON, note we must take care concerning the fact that JSON arrays are by definition 0-based, but we may want sequences with "offsets" other than 0.

**Comment by gwhitney** [comment]
On the other hand, Postgres databases can store arrays with arbitrary start and end indices (see https://www.postgresql.org/docs/current/arrays.html; note the start and end indices can vary by row) so that might be the ideal column type for storing sequence data. To implement this, one would have to look up how psycopg2 allows one to specify such a column, and how the indices are specified when data is inserted into the database.

**Comment by gwhitney** [comment]
Revisiting this database design. It is true that Postgres ARRAY columns are the ideal datatype for storing OEIS sequences, as they have arbitrary start and end indices. However, we are not using the Postgres database directly via psycopg2, but rather through the much higher-level interface provided by SQLalchemy "Object-Relational Mapping" which sets up a correspondence between Python objects and records in a table. And unfortunately the Python object created by a row with an Array that starts at index 3 and has values [6, 2, 8, 3, 1, 8, 5, 3] at positions 3 through 10 inclusive is exactly identical to that produced by a row with an array that has values [6, 2, 8, 3, 1, 8, 5, 3] at indices 0 through 7. So through the interface we are using, it's not possible to get at that index information stored in the Postgres database.

I don't think it's worth the effort at this point to switch what (level of) interface we use to the Postgres database. Instead, I propose the next iteration of the database design for the `sequences` table to be:
 - use the existing 'ID' and 'name' columns as they are;
 - drop the 'first_100_entries' column (which I figure was just for messing around anyway)
 - add an integer 'offset' column with the same meaning as in the OEIS.
 - add an ARRAY::string[] column 'values' -- so the first entry in this array will be the (string form of) the entry at the index given by offset, the next will be at index offset+1, etc. (We use strings because some OEIS integers are larger than any Postgres integer type.)
 - add a string 'raw_refs' column to be used for the data generated in #26.
 - leave database design for factorizations and/or discrete fourier transforms for the future.

Would love to have any comments or questions on that database design before I start to implement, as database architectures are just a bit stickier to update that other software changes (since there may be questions of migrating existing data/databases in case of future updates). Thanks!

**Comment by liam-mulhall** [comment]
> I don't think it's worth the effort at this point to switch what (level of) interface we use to the Postgres database.

Why?

I was under the impression that there wasn't much (if any) data in the database that would need to be migrated.

It seems to me that if there need to be big changes made to either the database or the interface to the database, now would be the time to make those changes. It would be relatively painless to change the interface now than to change it later when we're using the database in production.

**Comment by katestange** [comment]
About strings:  that seems fine.  Just curious, though:  python has arbitrarily large integers, right?  The problem is SQLalchemy doesn't translate those to something faithful?

And as for the 'first_100_entries' column, I honestly don't remember.  It's possible someone thought it wasn't efficient or possible to store or quickly retrieve the full sequence data in the table itself -- is that a possible problem?  Are there upper bounds we could reach?  

Also, there are use cases for grabbing just the first few entries.  For example, when choosing an OEIS sequence, the first few terms could automatically display in the parameter box along with the sequence name.  Is there any efficiency reason to store a few separately for such use cases?  Is grabbing the first few terms of a sequence from the 'values' column actually faster (for the user) than grabbing all the data?

**Comment by gwhitney** [comment]
> > I don't think it's worth the effort at this point to switch what (level of) interface we use to the Postgres database.
> 
> Why?
> 
> I was under the impression that there wasn't much (if any) data in the database that would need to be migrated.

It's not about migrating data; it's about the time and effort to identify a Postgres interface that supports all of the features of the Postgres ARRAY type (which is unique to Postgres; other SQL engines don't have ARRAYs -- I presume it's why Postgres was chosen for this project). The code is currently set up to use Flask - SQL Alchemy, which makes database access very convenient and compact to code with the Object Relational Mapping. I think one level down is psycopg2, so we'd have to investigate whether that supports different starting indices for Postgres ARRAYs. If not, then we'd be down to issuing raw SQL queries ourselves to the server, which would be a pain, and make our code a lot harder to understand at a glance. It just doesn't seem worth the time and effort as compared to just storing the actual starting index in a column, and using the array as if it always started at index 0, which is what the SQLalchemy interface supports. This isn't a primarily database project, it's a data visualization project, so I think we should take a path of less resistance here even if it is slightly disappointing not to take advantage of a feature in Postgres that's actually perfect for us.

All that said, it's certainly doable to keep Flask but drop down from SQLalchemy to direct use of psycopg2 or just raw SQL queries, and get it to work with the Postgres indices matching the official OEIS indices and no "offset" column in our records. If that's preferable to the team for whatever reasons (elegance, minimizing columns, not liking workarounds, whatever it might be), I can embark on that path. Let me know your thoughts on this.

**Comment by gwhitney** [comment]
> python has arbitrarily large integers, right? The problem is SQLalchemy doesn't translate those to something faithful?

No, the problem is that _Postgres_ does not have a numerical datatype that can hold an arbitrarily large integer. The only datatypes it has (that I am aware of) that can hold arbitrarily large units of data are strings, and "raw binary information" - basically just byte sequences. Might as well use strings, since we can then do some string matching (like find all of the entries with a given first digit) if we ever want to.

> And as for the 'first_100_entries' column, I honestly don't remember. It's possible someone thought it wasn't efficient or possible to store or quickly retrieve the full sequence data in the table itself -- is that a possible problem? Are there upper bounds we could reach?

I don't think there's any chance we will hit any capacity limits. Typically OEIS sequences have no more than 10000 entries in their b-files (there are  a few exceptions, though) and I think an array of 10000 entries is child's play for a mature database engine like Postgres.

> Also, there are use cases for grabbing just the first few entries. For example, when choosing an OEIS sequence, the first few terms could automatically display in the parameter box along with the sequence name. Is there any efficiency reason to store a few separately for such use cases? Is grabbing the first few terms of a sequence from the 'values' column actually faster (for the user) than grabbing all the data?

I have no idea of timing of grabbing the first 100 entries of an array of 10000 entries, vs. grabbing the entire value of a separate column that has just the first 100 entries. But (a) we can always re-optimize in such a way if we encounter slowness -- might as well keep the design lean for now, and (b) I suspect that in "exploratory" mode, it;s human actions that will generally be the rate-limiting step, not Postgres response time. But again, if I am wrong on (b) and the system gets sluggish, we'll be in better shape measuring where the bottlenecks are than guessing in advance what might be slow. I think there's a (coding) proverb about the dangers of "premature optimization."

**Comment by katestange** [comment]
Ok, thanks for the answers.  It all sounds good to me.  Regarding Liam's question, after reading the conversation, I don't feel a need to argue in favour of changing the interface.

**Comment by liam-mulhall** [comment]
Thanks for the detailed answer. I'm fine with using SQLAlchemy, as long as it's a library that isn't likely to fade away anytime soon. If, on the other hand, it isn't very popular or it doesn't look well-maintained, odds are we'll have to replace it somewhere down the road.

If you do your proposed workaround using SQLAlchemy, I think it needs to be very obvious in the code and in a doc somewhere what the workaround is and why it was done. I imagine you've already thought of this. I just think that when we're doing something unconventional, we need to be very explicit about it.

**Comment by gwhitney** [comment]
> it's a library that isn't likely to fade away

Well, given that it is used by Yelp and DropBox, and had its most recent release today, and has a clear road map for the next several releases, I think we are on safe ground with SQLalchemy. The schema I am proposing will look quite natural; after all, the OEIS itself stores the sequences with an offset field. If you didn't know that Postgres is actually capable of arbitrary starting indices (but that ability is masked by SQLalchemy's ORM), it's exactly how you would deal with non-zero starting indices. But yes, I will try to comment it all clearly.

OK, given all this conversation, I will proceed as outlined.

**Comment by gwhitney** [comment]
Another wrinkle: my hope is to set up the backend so that when it gets a request for a sequence that's not yet in the database, it grabs the b-file and makes the response, and then delegates the update to the database (which might eventually do heavyweight stuff like factor big numbers, etc) to a background process (that the http request won't block on). Two questions for y'all before I dive into this:

A) Reality check: is that overkill at this point? In other words, for now should I just grab the b-file and update the database all before responding to the http request (since I have to get the b-file anyway before the backend can respond, and at the moment just stuffing the values into the database is probably quicker than the trip out to the OEIS to get the b-file, which doesn't seem to be holding us up badly)?

B) If not and I should get things set up with some kind of background task execution at this juncture, I am considering adding another Flask extension for that purpose, namely Flask-Executor (see https://flask-executor.readthedocs.io/). Does that look OK to you guys, in terms of "liveness" and in terms of the functionality/interface it provides?

Thanks again for your thoughts and advice.

**Comment by katestange** [comment]
I'm not sure I can contribute too much on this, other than what you've already pointed out.  I think if you set it up so it is delegating the background process, that's going to be what we want in the long-run anyway (as we do more).  (Numberscope seemed really slow to get terms while I was testing the chaos visualizer with OEIS sequences -- are you aware of what's slowing it down?)

**Comment by gwhitney** [comment]
> Numberscope seemed really slow to get terms while I was testing the chaos visualizer with OEIS sequences -- are you aware of what's slowing it down?

No. If it is still that way in main now that everything is checked in, it would be great if you could file an issue with a specific example that reproducibly runs slowly.

**Comment by gwhitney** [comment]
I have a PR ready, including the background execution of the database update, to resolve this issue. I am just waiting to see if Steven H. is going to finish up PR #26 before I submit this, since it will create a rather involved merge between the two PRs, so it might be nicer if I merge my PR with his changes, rather than getting this in and forcing him to merge with mine...
