### ISSUE TITLE
Decide on a test runner for backscope

### ISSUE THREAD

**Issue by liam-mulhall** [numberscope/backscope#40]
According to [Real Python](https://realpython.com/python-testing/#choosing-a-test-runner), there are three popular ones:

* [unittest](https://docs.python.org/3/library/unittest.html)
* [nose](https://nose.readthedocs.io/en/latest/) or [nose2](https://github.com/nose-devs/nose2) (nose is old, we'd want nose2)
* [pytest](https://docs.pytest.org/en/7.1.x/)

unittest is built in. nose2 and pytest are the alternatives for people who don't want to use unittest.

**Comment by gwhitney** [comment]
I guess you are seeking feedback. My bias is to go with the one in the standard library unless/until we run up against some limitation of it. I imagine it won't be so hard to change if need be, especially not to Nose2 which is billed as an "extension" of unittest.

**Comment by gwhitney** [comment]
Well given the good support out there for all three, to me this definitely falls into the category of "whoever is willing to do the work at a first pass gets to pick" (at least among these three good candidates). So whoever gets to it should just use one of these.

**Comment by liam-mulhall** [comment]
> So whoever gets to it should just use one of these.

Okay, I've already started upgrading backscope and I installed and started using pytest, so pytest it is! :)
