### ISSUE TITLE
Should we ditch venv and use Poetry instead?

### ISSUE THREAD

**Issue by liam-mulhall** [numberscope/backscope#41]
I think setting up backscope could be made less painful with a better dependency management system. There are lots of options. The one that I find appealing is called [Poetry](https://python-poetry.org/). For more info, see:

https://hackersandslackers.com/python-poetry-package-manager/

Some highlights from the article:

> It sounds crazy, but Poetry makes covering all bases of a managing a Python project easy via its CLI and a single configuration file.

> [Poetry](https://python-poetry.org/) is arguably Python's most sophisticated dependency management option available today. Poetry goes far beyond dependencies, with features like generating .lock files, generating project scaffolding, and a ton of configuration options, all of which are handled via a simple CLI. If you're unsure how to cleanly and effectively structure and manage your Python projects, do yourself a favor and use Poetry.

> I'm well aware that tooling/architectural decisions in software are subjective preferences. Developers are not defined by their tools, blah blah, but look... at the risk of coming off as an ignorant novice, Poetry is objectively the best way to create, manage, and package Python projects. I don't have a horse in this race, but I'd go so far as to say that not embracing Poetry is a waste of your time.

I think the main advantage to using Poetry is that it will feel more like using npm/node_modules.

**Comment by gwhitney** [comment]
If you're making the effort to systematize installation of backscope on the Numberscope server, I am pretty much happy for you to use whatever tools/frameworks are going to make that as straightforward for you as possible, and I have no objection to Poetry in particular. (It's not really a wholesale "ditching" of venv in some sense, in that Poetry by default does create virtualenvs, it's just a different interface to creating and using virtualenvs. But once Poetry has created a virtualenv, you can if you want enter it just as you would one that had been created by venv itself. But I agree that once one is using Poetry there should no longer be any need to run venv directly.) Any case, feel free to go ahead with this or not at your discretion.

**Comment by liam-mulhall** [comment]
I've already started using it in a new branch where I'm updating backscope. I talked to Kate about using Poetry, and she seemed okay with using something that will make installing/running backscope easier, so I'm going to close this issue.
