### ISSUE TITLE
Error: Unparseable b-file line for ID 'A000521': -1 1

### ISSUE THREAD

**Issue by katestange** [numberscope/backscope#50]
When asking the backend to call sequence A000521, the b-file has a term for index -1, which seems to cause the backend to choke up.  To replicate, ask for `http://127.0.0.1:5000/api/get_oeis_values/A000521/50` and you will get the error that is the title of this issue.

**Comment by gwhitney** [comment]
Need to bump this in priority, as it hit again in testing https://github.com/numberscope/frontscope/pull/230
