### ISSUE TITLE
README setup omits guidance at confusing step

### ISSUE THREAD

**Issue by gwhitney** [numberscope/backscope#7]
In trying to set up this backend for the first time according to the README, things went fine until I got to the step `python manage.py db init`, which ran but produced the message
```
  Please edit configuration/connection/logging settings in
  '/home/glen/code/NumberscopeFlask/migrations/alembic.ini' before proceeding.
```
There's nothing in the README about how, why, or what to edit in this .ini file. It should either give directions, or let the reader know it's OK to leave the file as is.

**Comment by gwhitney** [comment]
(I will file a PR to fix this once I figure out, with everyone's help, how to proceed.

**Comment by khaledallen** [comment]
If it's useful, here's my `alembic.ini` which does work once everything else is set up:

```
# A generic, single database configuration.

[alembic]
# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false


# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
```

**Comment by gwhitney** [comment]
That was super helpful, khaledallen -- the file you posted is identical to the automatically generated one. Hence I just filed a PR that says it's OK to ignore the message from alembic.
