### ISSUE TITLE
backscope should log to a file

### ISSUE THREAD

**Issue by liammulh** [numberscope/backscope#72]
In production, `backscope` should log to a file. We can do this with Flask or with journalctl.

**Comment by gwhitney** [comment]
From Liam via Slack:
Also, I discovered that we have logging configured for backscope. See https://github.com/numberscope/backscope/blob/297673f219d30eb363a48e7e86c5f7f4589d85ac/flaskr/__init__.py#L38-L44. I SSH’d to the CU server, and sure enough there are logs in the api.log file.
