### ISSUE TITLE
Add an endpoint to return the running git revision fingerprint

### ISSUE THREAD

**Issue by gwhitney** [numberscope/backscope#75]
This will allow us to be certain of what version of the backend is actually running on a given server

**Comment by katestange** [comment]
Question about this:  when we eventually have deployment scripts going on the server, git will be installed on the server and the scripts will `git pull` and then run the setup commands etc, right?  

So a solution which involves the following: -- from inside the running backend, creating a subprocess that just calls git to ask about the git revision hash -- is appropriate?  E.g., https://stackoverflow.com/a/21901260 

If that seems appropriate, I think I could try to do this.

**Comment by gwhitney** [comment]
Yes, git is installed on the server, and the code to run is loaded onto the server via `git pull`. Remember now that we have a test harness in place, a PR for this issue should document the new endpoint and provide a test of the new endpoint. Thanks!

**Comment by katestange** [comment]
@gwhitney wrote "I recommend a single endpoint that returns the version number and the latest git commit id."  What do you mean by "version number" -- version number of what?

**Comment by katestange** [comment]
Also, another question, how can I test the new endpoint?  the hash is always different

**Comment by katestange** [comment]
Ok, I'm stuck on deciding what to do for testing, but I committed my changes so you can see them.  Here's the beginning of a test: [https://github.com/katestange/backscope/blob/githash/flaskr/nscope/test/test_get_hash.py](https://github.com/katestange/backscope/blob/githash/flaskr/nscope/test/test_get_hash.py)
Maybe @Vectornaut has suggestions.

**Comment by gwhitney** [comment]
> @gwhitney wrote "I recommend a single endpoint that returns the version number and the latest git commit id." What do you mean by "version number" -- version number of what?

Oh! Most python projects have a "pyproject.toml" file (see https://packaging.python.org/en/latest/tutorials/packaging-projects/) that specifies a current version number of the project. That's updated (manually) when a new release of the project is made. But I see that backscope has no such thing. So I guess the current git hash is the best one can do at the moment.

**Comment by gwhitney** [comment]
> Also, another question, how can I test the new endpoint? the hash is always different. I could just test that it returns appropriately formatted JSON and ignore the actual hash.

Well, I think the test should just grab the hash, too, and match it against what it gets from the endpoint...

**Comment by gwhitney** [comment]
Yeah, you're testing that the server can deliver the hash.
