### ISSUE TITLE
OEIS sequence offset is never being set

### ISSUE THREAD

**Issue by gwhitney** [numberscope/backscope#77]
In one of the refactorings, the step where the sequence offset is deduced from OEIS data and stored in the database got lost. It needs to be restored for the correctness of  the sequence data.

**Comment by Vectornaut** [comment]
The test `TestGetOEISValues` in [pull request #84](https://github.com/numberscope/backscope/pull/84) is sensitive to this issue. We should stop skipping that test (by removing the skip decorator) when the issue is fixed.

**Comment by gwhitney** [comment]
OK, I am crossing my fingers that the logging PR is close enough and building a PR for this _on top of_ that one. Once that one merges, I will rebase mine and file it.
