### ISSUE TITLE
spelling error in docs

### ISSUE THREAD

**Issue by katestange** [numberscope/backscope#97]
https://github.com/numberscope/backscope/blob/a63d3cf3a212b2a00a371aa99f9de36177174bef/doc/install-postgres.md?plain=1#L46

**Comment by gwhitney** [comment]
Could we fold this into #92 and deal with it then rather making a separate PR for it?

**Comment by katestange** [comment]
yes please!

**Comment by katestange** [comment]
closing, i did as advised and put this into #92
